# Generated by Django 5.1.5 on 2025-01-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced_payment_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='Payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
    ]
