# Generated by Django 5.1.5 on 2025-01-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orderplaced_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='Payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
    ]
